version: '3.8'

services:
  # 1. IL DATABASE
  db:
    image: mongo:latest
    container_name: mongodb_beach
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. IL SERVER (TORNADO)
  web:
    build: .
    container_name: tornado_server
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://db:27017
    # Questo assicura che il server riparta se crasha per un errore di connessione iniziale
    restart: always

  # 3. IL PUBLISHER
  publisher:
    build: .
    container_name: match_publisher
    depends_on:
      - web
    # Sovrascriviamo il comando del Dockerfile per lanciare il publisher
    command: python publisher.py
    environment:
      - SERVER_URL=http://web:8888
    restart: on-failure
    # Aspettiamo qualche secondo extra per essere sicuri che Tornado abbia caricato i match
    entrypoint: ["/bin/sh", "-c", "sleep 5 && python publisher.py"]

volumes:
  mongo_data: