version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_beach
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: tornado_server
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://db:27017
    restart: always

  publisher:
    build: .
    container_name: match_publisher
    depends_on:
      - web
    command: python publisher.py
    environment:
      - SERVER_URL=http://web:8888
    restart: on-failure
    entrypoint: ["/bin/sh", "-c", "sleep 5 && python publisher.py"]

volumes:
  mongo_data: